apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: funqy-quarkus-serverless-cloudevent-s2i
spec:
  template:
    metadata:
      name: funqy-quarkus-serverless-cloudevent-s2i-v1
      annotations:
        autoscaling.knative.dev/target: "1"
    spec:
      containers:
        - image: quay.io/skoussou/funqy-quarkus-serverless-cloudevent-s2i